### PR TITLE
New tests.

### PR DESCRIPTION
**Pull request by Altai-man**
Tests for cygwin and DOS were obviously dropped. Also, I'm not sure what to do with MacOS - someone with Mac is needed to write them.
I'm on a gentoo machine now, so tests for windows "should" be working, but it'll be great if someone on windows tests them and fixes it.

### CODE REVIEW

**Comment by azawawi** [comment]
Great. I will test them on windows. We have travis CI enabled on for MacOSX :+1: 

Please see:
https://github.com/azawawi/perl6-file-which/blob/master/.travis.yml#L7
and
https://travis-ci.org/azawawi/perl6-file-which/builds/124118881

**Comment by Altai-man** [comment]
Oh, it's great then. It seems the tests work for MacOSX as for Unix and they pass successfully, so there is no problem.
Also, this package is a bit old and I assume removing of "use lib 'Lib'", which is unnecessary now, is rather good. And I've notice that indentation of emacs(4 spaces instead of 2) is not like yours, so I think two commits are coming, don't merge it yet...

**Comment by azawawi** [comment]
Cool. I am holding merging until https://ci.appveyor.com/project/azawawi/perl6-file-which works.

**Comment by azawawi** [comment]
Also I use `use lib 'lib'` as a safeguard in case prove was run without `perl6 -Ilib`. Also sometimes one forgets and adds an `prove -Ilib` instead of `prove -e 'perl6 -Ilib'`.

**Comment by Altai-man** [comment]
And we have the failed build. Okay, then fixes are coming.

**Comment by Altai-man** [comment]
After all, I need a windows to properly debug it. I failed to install rakudo using virtual machine, so I'm not sure what to do. Any ideas?

**Comment by azawawi** [comment]
I will debug it after merging it.

**Comment by azawawi** [comment]
Thanks :+1:

**Pull request merged**
