### PR TITLE
Modernize distribution

### LINKED ISSUE #21: Linux dependency on Win32::Registry
On Linux still depends on Win32::Registry to install.

### PR DESCRIPTION
**Pull request by ugexe**
This accommodates the Perl6 -> Raku name change, brings the CI related items up to date, and conditionally uses `Win32::Registry` so this module works on non-windows systems again.

Fixes #21

### CODE REVIEW

**Comment by ugexe** [comment]
This won't work until `Win32::Registry` marks its various exported subs as `our`

**Comment by ugexe** [comment]
@sdondley fyi your last update broken this module on non-windows systems. These changes attempt to fix it but more accommodations need to be made to `Win32::Registry`

**Comment by sdondley** [comment]
OK, sorry about that. I'll see what I can figure out with the failing test on windows.

**Comment by sdondley** [comment]
I cloned your `updates` branch to a windows machine and ran `prove6 --lib -v t` and all tests assed for me.

**Comment by ugexe** [comment]
Ah, I forgot to install `Win32::Registry` first. However, `Win32::Registry` tests depend on `Test::Output` but it isn't declared as a dependency and thus it won't be installed due to failing tests.

**Comment by sdondley** [comment]
I don't follow. The `Win32::Registry` module does not use `Test::Output`.

**Comment by ugexe** [comment]
Because you deleted it 5 minutes ago -- https://github.com/sdondley/Win32-Registry/commit/d4d2bc29391e06e6abeb9ed9f4c250f3757a7d71#diff-8de697a21e1c6828677cc0c1baf23fed356f76e26ffdce00f08060c487391ce4L5

**Comment by sdondley** [comment]
Oh, ha. Yeah, that author test code file is some autogenerated code I wrote a while ago. Gotta clean that up.

**Comment by azawawi** [comment]
@ugexe Good evening. Are there any further commits or shall I merge it? The only minor blocker so far is `examples/02-whence.rakumod` file extension.

**Comment by ugexe** [comment]
@azawawi Should be good now

**Comment by azawawi** [comment]
Thanks 👍

**Pull request merged**
